# NIST

The National Institute of Standards and Technology (NIST) supplies Carsus with atomic weights, ionization energies and ground levels configurations.

## Atomic Weights

Provided by the NIST Atomic Weights and Isotopic Compositions Database.

In [1]:
from carsus.io.nist import NISTWeightsComp

 ChiantiPy version 0.8.4
 found PyQt5 widgets
 using PyQt5 widgets

In [2]:
nist_weights = NISTWeightsComp('H-O')

[ carsus.io.nist.weightscomp][   INFO] - Downloading data from the NIST Atomic Weights and Isotopic Compositions Database. (weightscomp.py:49)

In [3]:
nist_weights.base

              symbol       name       mass
atomic_number
1                  H   Hydrogen   1.007975
2                 He     Helium   4.002602
3                 Li    Lithium   6.967500
4                 Be  Beryllium   9.012183
5                  B      Boron  10.813500
6                  C     Carbon  12.010600
7                  N   Nitrogen  14.006855
8                  O     Oxygen  15.999400

## Ionization Energies and Ground Levels

Provided by the NIST Atomic Spectra Database.

In [4]:
from carsus.io.nist import NISTIonizationEnergies

In [5]:
nist_ioniz = NISTIonizationEnergies('H-O')

[  carsus.io.nist.ionization][   INFO] - Downloading ionization energies from the NIST Atomic Spectra Database. (ionization.py:65)

In [6]:
nist_ioniz.base

atomic_number  ion_charge
1              0              13.598435
2              0              24.587389
               1              54.417765
3              0               5.391715
               1              75.640097
               2             122.454359
4              0               9.322699
               1              18.211150
               2             153.896205
               3             217.718586
5              0               8.298019
               1              25.154830
               2              37.930590
               3             259.371500
               4             340.226023
6              0              11.260288
               1              24.383154
               2              47.887780
               3              64.493520
               4             392.090518
               5             489.993198
7              0              14.534130
               1              29.601250
               2              47.445300
               3              77.473500
               4              97.890100
               5             552.067330
               6             667.046121
8              0              13.618055
               1              35.121120
               2              54.935540
               3              77.413500
               4             113.899000
               5             138.118900
               6             739.326830
               7             871.409883
Name: ionization_energy, dtype: float64

In [7]:
nist_ioniz.get_ground_levels()

    atomic_number  ion_charge  g  energy
0               1           0  2     0.0
1               2           0  1     0.0
2               2           1  2     0.0
3               3           0  2     0.0
4               3           1  1     0.0
5               3           2  2     0.0
6               4           0  1     0.0
7               4           1  2     0.0
8               4           2  1     0.0
9               4           3  2     0.0
10              5           0  2     0.0
11              5           1  1     0.0
12              5           2  2     0.0
13              5           3  1     0.0
14              5           4  2     0.0
15              6           0  1     0.0
16              6           1  2     0.0
17              6           2  1     0.0
18              6           3  2     0.0
19              6           4  1     0.0
20              6           5  2     0.0
21              7           0  4     0.0
22              7           1  1     0.0
23              7           2  2     0.0
24              7           3  1     0.0
25              7           4  2     0.0
26              7           5  1     0.0
27              7           6  2     0.0
28              8           0  5     0.0
29              8           1  4     0.0
30              8           2  1     0.0
31              8           3  2     0.0
32              8           4  1     0.0
33              8           5  2     0.0
34              8           6  1     0.0
35              8           7  2     0.0